# BINNING DATA SMOOTHING

### EQUI FREQUENCY BINNING

In [1]:
def equifreq(arr1, m):
    arr1.sort()
    a = len(arr1)
    n = int(a / m)
    for i in range(0, m):
        arr = []
        for j in range(i * n, (i + 1) * n):
            if j >= a:
                break
            arr.append(arr1[j])
        print("Bin", i+1, ":", arr)

data = [5, 10, 11, 15, 13, 35, 50, 55, 72, 92, 204, 215]

m = 3

print("Equal frequency binning")
equifreq(data, m)

Equal frequency binning
Bin 1 : [5, 10, 11, 13]
Bin 2 : [15, 35, 50, 55]
Bin 3 : [72, 92, 204, 215]

### EQUI FREQUENCY BINNING BY MEAN

In [3]:

def equifreq(arr1, m):
    arr1.sort()
    a = len(arr1)
    n = int(a / m)
    
    for i in range(0, m):
        arr = []
        for j in range(i * n, (i + 1) * n):
            if j >= a:
                break
            arr.append(arr1[j])
        
        # Calculate mean of the current bin
        mean = sum(arr) / len(arr) 
        
        print("Bin", i+1,":", [mean] * len(arr))

data = [5, 10, 11, 15, 13, 35, 50, 55, 72, 92, 204, 215]
m = 3

print("Equal frequency binning with bin means")
equifreq(data, m)

Equal frequency binning with bin means
Bin 1 : [9.75, 9.75, 9.75, 9.75]
Bin 2 : [38.75, 38.75, 38.75, 38.75]
Bin 3 : [145.75, 145.75, 145.75, 145.75]

### EQUI FREQUENCY BINNING BY BIN BOUNDARIES

In [4]:
def equifreq(arr1, m):
    arr1.sort()
    a = len(arr1)
    n = int(a / m)

    for i in range(m):
        arr = []
        for j in range(i * n, (i + 1) * n):
            if j >= a:
                break
            arr.append(arr1[j])

    
        min_val = min(arr)
        max_val = max(arr)
        
        # Replace each value with nearest boundary
        replaced = []
        for val in arr:
            if abs(val - min_val) <= abs(val - max_val):
                replaced.append(min_val)
            else:
                replaced.append(max_val)

        print(f"Bin {i+1}: {replaced}")

data = [5, 10, 11, 15, 13, 35, 50, 55, 72, 92, 204, 215]
m = 3

print("Equal frequency binning with values replaced by nearest boundaries")
equifreq(data, m)

Equal frequency binning with values replaced by nearest boundaries
Bin 1: [5, 13, 13, 13]
Bin 2: [15, 15, 55, 55]
Bin 3: [72, 72, 215, 215]

### EQUI FREQUENCY BINNING BY MEDIAN

In [6]:


def equifreq(arr, m):
    arr.sort()
    a = len(arr)
    n = int(a / m)

    for i in range(m):
        bins = []
        for j in range(i * n, (i + 1) * n):
            if j >= a:
                break
            bins.append(arr[j])
        
        # Calculate median without built-in function
        mid = len(bins) // 2
        if len(bins) % 2 == 0:
            median_val = (bins[mid - 1] + bins[mid]) / 2
        else:
            median_val = bins[mid]
        
        
        print(f"Bin {i + 1}:", [median_val] * len(bins))

data = [5, 10, 11, 15, 13, 35, 50, 55, 72, 92, 204, 215]
m = 3

print("Equal frequency binning with values replaced by median ")
equifreq(data, m)

Equal frequency binning with values replaced by median
Bin 1: [10.5, 10.5, 10.5, 10.5]
Bin 2: [42.5, 42.5, 42.5, 42.5]
Bin 3: [148.0, 148.0, 148.0, 148.0]

### EQUI FREQUENCY BINNING BY CUT METHOD

In [7]:
import pandas as pd
df=pd.read_excel("D:/marks.xlsx")
df

   roll-no  marks
0        1     90
1        2     87
2        3     78
3        4     67
4        5     89
5        6     98
6        7     60
7        8     55
8        9     34
9       10     23

In [9]:
df['grade']=pd.cut(df['marks'],bins=[0,50,70,90,100],labels=['P','B','A','O'])
df

   roll-no  marks grade
0        1     90     A
1        2     87     A
2        3     78     A
3        4     67     B
4        5     89     A
5        6     98     O
6        7     60     B
7        8     55     B
8        9     34     P
9       10     23     P

In [10]:
df['age']=[21,22,21,18,19,23,67,90,8,9]

In [11]:
df['age_class']=pd.cut(df['age'],bins=[0,17,59,100],labels=['child','adult','senior'])
df

   roll-no  marks grade  age age_class
0        1     90     A   21     adult
1        2     87     A   22     adult
2        3     78     A   21     adult
3        4     67     B   18     adult
4        5     89     A   19     adult
5        6     98     O   23     adult
6        7     60     B   67    senior
7        8     55     B   90    senior
8        9     34     P    8     child
9       10     23     P    9     child

# -----------------------------------------------------------------------